{% set name = "tangram_bondorder" %}


package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0')|int }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - pychimera     >=0.2.6
    - libtangram

about:
  home: http://github.com/insilichem/tangram_bondorder
  license: MIT
  license_family: MIT

  summary: 'Bond order perception extension for UCSF Chimera'

  description: |
    Bond order perception extension for UCSF Chimera
  doc_url: http://tangram-suite.readthedocs.io/en/latest/tangram_bondorder.html
  dev_url: https://github.com/insilichem/tangram_bondorder


